In [1]:
import math
import io

In [2]:
import numpy as np
import pandas as pd

import matplotlib
import matplotlib.pyplot as pp

%matplotlib inline

In [3]:
import scipy.stats
import scipy.optimize
import scipy.spatial

In [4]:
poll = pd.read_csv('poll.csv')

In [5]:
poll.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   vote    1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB


In [6]:
poll.head()

vote
0  Brown
1  Green
2  Brown
3  Brown
4  Brown

In [7]:
poll.vote.value_counts(normalize=True)

Brown    0.511
Green    0.489
Name: vote, dtype: float64

In [10]:
np.random.rand(5)

array([0.02903664, 0.27202306, 0.90368687, 0.19656119, 0.6571866 ])

In [9]:
np.random.rand(5) * 10

array([8.27972495, 5.87271605, 4.83314009, 0.62747745, 1.53149157])

In [11]:
np.random.rand(5) < 0.51

array([ True, False, False,  True, False])

In [12]:
# Convert Boolean value into a string
np.where(np.random.rand(5) < 0.51, 'Alita', 'Major')

array(['Major', 'Alita', 'Alita', 'Major', 'Alita'], dtype='<U5')

In [16]:
# Wrap everything in a dataframe and make a function out of it
def sample(brown, n=1000):
    return pd.DataFrame({'vote': np.where(np.random.rand(n) < brown, 'Brown', 'Green')})

In [33]:
s = sample(0.51, n=1000)

In [34]:
s.vote.value_counts(normalize=True)

Brown    0.518
Green    0.482
Name: vote, dtype: float64